### ISSUE TITLE
When will the results of our programming assignments be released?

### ISSUE THREAD

**Issue by hellozts4120** [NCTU-CSE-Introduction-to-Algorithms/assignment-3-announcement-and-discussion#1]
We have done three programming assignments, but none of their results have been released. I just wonder when can we see the scores of our programming assignments?
Thanks :)

**Comment by yoyolicoris** [comment]
Same question

**Comment by PeterDaveHello** [comment]
Sorry for the late reply, please take a look at the latest announcement on E3 platform, thanks.
